name: 'Back Merge'
description: 'Create a back-merge PR from main to develop after release'
author: 'Banua Coder'

inputs:
  version:
    description: 'The version that was released'
    required: true
  base-branch:
    description: 'The branch to merge into'
    required: false
    default: 'develop'
  source-branch:
    description: 'The branch to merge from'
    required: false
    default: 'main'
  github-token:
    description: 'GitHub token for creating PR'
    required: true
  auto-merge:
    description: 'Automatically merge if no conflicts'
    required: false
    default: 'false'
  conflict-resolution:
    description: 'How to resolve version conflicts (ours=keep develop version, theirs=use main version, manual)'
    required: false
    default: 'ours'

outputs:
  pr-number:
    description: 'The PR number created'
    value: ${{ steps.create-pr.outputs.pr_number }}
  pr-url:
    description: 'The PR URL'
    value: ${{ steps.create-pr.outputs.pr_url }}
  has-conflicts:
    description: 'Whether there are merge conflicts'
    value: ${{ steps.check-conflicts.outputs.has_conflicts }}

runs:
  using: 'composite'
  steps:
    - name: Setup Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create back-merge branch
      id: create-branch
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        SOURCE="${{ inputs.source-branch }}"
        BASE="${{ inputs.base-branch }}"
        BRANCH_NAME="chore/back-merge-$VERSION"

        # Fetch all branches
        git fetch origin

        # Create branch from source
        git checkout -b "$BRANCH_NAME" "origin/$SOURCE"

        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "✅ Created branch: $BRANCH_NAME"

    - name: Check for conflicts
      id: check-conflicts
      shell: bash
      run: |
        BASE="${{ inputs.base-branch }}"
        BRANCH="${{ steps.create-branch.outputs.branch_name }}"

        # Try to merge base into our branch to check for conflicts
        git fetch origin "$BASE"

        if git merge --no-commit --no-ff "origin/$BASE" 2>/dev/null; then
          echo "has_conflicts=false" >> $GITHUB_OUTPUT
          git merge --abort 2>/dev/null || true
          echo "✅ No conflicts detected"
        else
          echo "has_conflicts=true" >> $GITHUB_OUTPUT
          git merge --abort 2>/dev/null || true
          echo "⚠️ Conflicts detected"
        fi

    - name: Resolve version conflicts
      if: steps.check-conflicts.outputs.has_conflicts == 'true' && inputs.conflict-resolution != 'manual'
      shell: bash
      run: |
        RESOLUTION="${{ inputs.conflict-resolution }}"
        BASE="${{ inputs.base-branch }}"

        # Common version files
        VERSION_FILES="config/app.php package.json pubspec.yaml composer.json version.txt gradle.properties"

        git fetch origin "$BASE"

        # Attempt merge
        git merge "origin/$BASE" --no-commit || true

        # Resolve version file conflicts
        for file in $VERSION_FILES; do
          if [ -f "$file" ] && git diff --name-only --diff-filter=U | grep -q "$file"; then
            echo "Resolving conflict in $file using $RESOLUTION strategy"
            if [ "$RESOLUTION" = "theirs" ]; then
              git checkout --theirs "$file"
            else
              git checkout --ours "$file"
            fi
            git add "$file"
          fi
        done

        # Check if there are still unresolved conflicts
        if git diff --name-only --diff-filter=U | grep -v -E "$(echo $VERSION_FILES | tr ' ' '|')" | head -1; then
          echo "⚠️ There are still unresolved conflicts in non-version files"
        fi

        # Complete the merge if possible
        git commit -m "chore: back-merge ${{ inputs.version }} to $BASE" || true

    - name: Push branch
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        BRANCH="${{ steps.create-branch.outputs.branch_name }}"
        git push origin "$BRANCH"
        echo "✅ Pushed branch: $BRANCH"

    - name: Create Pull Request
      id: create-pr
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        VERSION="${{ inputs.version }}"
        BASE="${{ inputs.base-branch }}"
        BRANCH="${{ steps.create-branch.outputs.branch_name }}"
        HAS_CONFLICTS="${{ steps.check-conflicts.outputs.has_conflicts }}"

        BODY="## Back-merge $VERSION to $BASE

        This PR merges the release \`$VERSION\` back to \`$BASE\`.

        ### Changes included:
        - Release $VERSION changes
        - Changelog updates

        "

        if [ "$HAS_CONFLICTS" = "true" ]; then
          BODY="$BODY
        ⚠️ **Note**: This PR had merge conflicts. Version file conflicts were auto-resolved using the \`${{ inputs.conflict-resolution }}\` strategy. Please review carefully.
        "
        fi

        PR_URL=$(gh pr create \
          --base "$BASE" \
          --head "$BRANCH" \
          --title "chore: back-merge $VERSION to $BASE" \
          --body "$BODY")

        PR_NUMBER=$(echo "$PR_URL" | grep -o '[0-9]*$')

        echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        echo "✅ Created PR: $PR_URL"

    - name: Auto-merge if enabled
      if: inputs.auto-merge == 'true' && steps.check-conflicts.outputs.has_conflicts == 'false'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        PR_NUMBER="${{ steps.create-pr.outputs.pr_number }}"
        gh pr merge "$PR_NUMBER" --merge --auto
        echo "✅ Auto-merge enabled for PR #$PR_NUMBER"
