name: 'Back Merge'
description: 'Create a back-merge PR from main to develop after release'
author: 'Banua Coder'

inputs:
  version:
    description: 'The version that was released'
    required: true
  base-branch:
    description: 'The branch to merge into'
    required: false
    default: 'develop'
  source-branch:
    description: 'The branch to merge from'
    required: false
    default: 'main'
  github-token:
    description: 'GitHub token for creating PR'
    required: true
  auto-merge:
    description: 'Automatically merge if no conflicts'
    required: false
    default: 'false'
  conflict-resolution:
    description: 'How to resolve version conflicts (keep-higher=keep higher version, keep-develop=always keep develop version, keep-main=use main version, manual=no auto-resolution)'
    required: false
    default: 'keep-higher'

outputs:
  pr-number:
    description: 'The PR number created'
    value: ${{ steps.create-pr.outputs.pr_number }}
  pr-url:
    description: 'The PR URL'
    value: ${{ steps.create-pr.outputs.pr_url }}
  has-conflicts:
    description: 'Whether there are merge conflicts'
    value: ${{ steps.check-conflicts.outputs.has_conflicts }}

runs:
  using: 'composite'
  steps:
    - name: Setup Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create back-merge branch
      id: create-branch
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        SOURCE="${{ inputs.source-branch }}"
        BASE="${{ inputs.base-branch }}"
        BRANCH_NAME="chore/back-merge-$VERSION"

        # Fetch all branches
        git fetch origin

        # Create branch from source
        git checkout -b "$BRANCH_NAME" "origin/$SOURCE"

        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "âœ… Created branch: $BRANCH_NAME"

    - name: Check for conflicts
      id: check-conflicts
      shell: bash
      run: |
        BASE="${{ inputs.base-branch }}"
        BRANCH="${{ steps.create-branch.outputs.branch_name }}"

        # Try to merge base into our branch to check for conflicts
        git fetch origin "$BASE"

        if git merge --no-commit --no-ff "origin/$BASE" 2>/dev/null; then
          echo "has_conflicts=false" >> $GITHUB_OUTPUT
          git merge --abort 2>/dev/null || true
          echo "âœ… No conflicts detected"
        else
          echo "has_conflicts=true" >> $GITHUB_OUTPUT
          git merge --abort 2>/dev/null || true
          echo "âš ï¸ Conflicts detected"
        fi

    - name: Resolve version conflicts
      if: steps.check-conflicts.outputs.has_conflicts == 'true' && inputs.conflict-resolution != 'manual'
      shell: bash
      run: |
        RESOLUTION="${{ inputs.conflict-resolution }}"
        BASE="${{ inputs.base-branch }}"

        # Common version files and their version extraction patterns
        VERSION_FILES="config/app.php package.json pubspec.yaml composer.json version.txt gradle.properties build.gradle.kts build.gradle"

        git fetch origin "$BASE"

        # Attempt merge
        git merge "origin/$BASE" --no-commit || true

        # Function to extract version from a file
        extract_version() {
          local file="$1"
          local content="$2"

          case "$file" in
            config/app.php)
              echo "$content" | grep -oP "version.*?'\K[0-9]+\.[0-9]+\.[0-9]+" | head -1
              ;;
            package.json|composer.json)
              echo "$content" | grep -oP '"version"\s*:\s*"\K[0-9]+\.[0-9]+\.[0-9]+' | head -1
              ;;
            pubspec.yaml)
              echo "$content" | grep -oP '^version:\s*\K[0-9]+\.[0-9]+\.[0-9]+' | head -1
              ;;
            version.txt)
              echo "$content" | grep -oP '[0-9]+\.[0-9]+\.[0-9]+' | head -1
              ;;
            gradle.properties)
              echo "$content" | grep -oP 'version\s*=\s*\K[0-9]+\.[0-9]+\.[0-9]+' | head -1
              ;;
            build.gradle|build.gradle.kts)
              echo "$content" | grep -oP "version\s*=\s*['\"]?\K[0-9]+\.[0-9]+\.[0-9]+" | head -1
              ;;
          esac
        }

        # Function to compare semver versions (returns 0 if v1 >= v2, 1 otherwise)
        version_gte() {
          local v1="$1"
          local v2="$2"

          if [ -z "$v1" ]; then return 1; fi
          if [ -z "$v2" ]; then return 0; fi

          # Split versions into arrays
          IFS='.' read -r v1_major v1_minor v1_patch <<< "$v1"
          IFS='.' read -r v2_major v2_minor v2_patch <<< "$v2"

          # Compare major
          if [ "$v1_major" -gt "$v2_major" ]; then return 0; fi
          if [ "$v1_major" -lt "$v2_major" ]; then return 1; fi

          # Compare minor
          if [ "$v1_minor" -gt "$v2_minor" ]; then return 0; fi
          if [ "$v1_minor" -lt "$v2_minor" ]; then return 1; fi

          # Compare patch
          if [ "$v1_patch" -ge "$v2_patch" ]; then return 0; fi
          return 1
        }

        # Resolve version file conflicts
        for file in $VERSION_FILES; do
          if [ -f "$file" ] && git diff --name-only --diff-filter=U | grep -q "^${file}$"; then
            echo "ðŸ” Found conflict in $file"

            # In this merge context:
            # --ours = current branch (back-merge branch, which is from main)
            # --theirs = the branch being merged in (develop)

            if [ "$RESOLUTION" = "keep-higher" ]; then
              # Get both versions
              MAIN_VERSION=$(git show :2:"$file" 2>/dev/null | grep -oP "version.*?['\"]?\K[0-9]+\.[0-9]+\.[0-9]+" | head -1 || echo "")
              DEVELOP_VERSION=$(git show :3:"$file" 2>/dev/null | grep -oP "version.*?['\"]?\K[0-9]+\.[0-9]+\.[0-9]+" | head -1 || echo "")

              echo "  Main version: ${MAIN_VERSION:-unknown}"
              echo "  Develop version: ${DEVELOP_VERSION:-unknown}"

              if version_gte "$DEVELOP_VERSION" "$MAIN_VERSION"; then
                echo "  âœ… Keeping develop version ($DEVELOP_VERSION >= $MAIN_VERSION)"
                git checkout --theirs "$file"
              else
                echo "  âœ… Keeping main version ($MAIN_VERSION > $DEVELOP_VERSION)"
                git checkout --ours "$file"
              fi
            elif [ "$RESOLUTION" = "keep-develop" ]; then
              echo "  âœ… Keeping develop version (strategy: keep-develop)"
              git checkout --theirs "$file"
            elif [ "$RESOLUTION" = "keep-main" ]; then
              echo "  âœ… Keeping main version (strategy: keep-main)"
              git checkout --ours "$file"
            fi

            git add "$file"
          fi
        done

        # Check if there are still unresolved conflicts
        REMAINING_CONFLICTS=$(git diff --name-only --diff-filter=U | head -5)
        if [ -n "$REMAINING_CONFLICTS" ]; then
          echo "âš ï¸ There are still unresolved conflicts in:"
          echo "$REMAINING_CONFLICTS"
        fi

        # Complete the merge if possible
        git commit -m "chore: back-merge ${{ inputs.version }} to $BASE" || true

    - name: Push branch
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        BRANCH="${{ steps.create-branch.outputs.branch_name }}"
        git push origin "$BRANCH"
        echo "âœ… Pushed branch: $BRANCH"

    - name: Create Pull Request
      id: create-pr
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        VERSION="${{ inputs.version }}"
        BASE="${{ inputs.base-branch }}"
        BRANCH="${{ steps.create-branch.outputs.branch_name }}"
        HAS_CONFLICTS="${{ steps.check-conflicts.outputs.has_conflicts }}"

        RESOLUTION="${{ inputs.conflict-resolution }}"

        # Build PR body
        BODY="## Back-merge $VERSION to $BASE"
        BODY="$BODY"$'\n'$'\n'"This PR merges the release \`$VERSION\` back to \`$BASE\`."
        BODY="$BODY"$'\n'$'\n'"### Changes included"
        BODY="$BODY"$'\n'"- Release $VERSION changes"
        BODY="$BODY"$'\n'"- Changelog updates"

        if [ "$HAS_CONFLICTS" = "true" ]; then
          RESOLUTION_DESC=""
          case "$RESOLUTION" in
            keep-higher)
              RESOLUTION_DESC="Version conflicts were resolved by keeping the **higher version number**."
              ;;
            keep-develop)
              RESOLUTION_DESC="Version conflicts were resolved by keeping the **develop branch version**."
              ;;
            keep-main)
              RESOLUTION_DESC="Version conflicts were resolved by keeping the **main branch version**."
              ;;
            manual)
              RESOLUTION_DESC="Version conflicts require **manual resolution**."
              ;;
          esac

          BODY="$BODY"$'\n'$'\n'"> [!WARNING]"
          BODY="$BODY"$'\n'"> This PR had merge conflicts. $RESOLUTION_DESC Please review carefully."
        fi

        PR_URL=$(gh pr create \
          --base "$BASE" \
          --head "$BRANCH" \
          --title "chore: back-merge $VERSION to $BASE" \
          --body "$BODY")

        PR_NUMBER=$(echo "$PR_URL" | grep -o '[0-9]*$')

        echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        echo "âœ… Created PR: $PR_URL"

    - name: Auto-merge if enabled
      if: inputs.auto-merge == 'true' && steps.check-conflicts.outputs.has_conflicts == 'false'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        PR_NUMBER="${{ steps.create-pr.outputs.pr_number }}"
        gh pr merge "$PR_NUMBER" --merge --auto
        echo "âœ… Auto-merge enabled for PR #$PR_NUMBER"

