# Example workflow for PHP packages (Packagist)
# Copy this file to your project's .github/workflows/release.yml

name: Release

on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    uses: banua-coder/banua-coder-workflow/.github/workflows/release.yml@v1
    with:
      project-type: php-package
      main-branch: main
      develop-branch: develop
      changelog-format: keepachangelog
      php-version: '8.2'
    secrets: inherit

  # Publish when tag is pushed
  # Note: Packagist auto-detects tags via GitHub webhook
  # This job just runs tests and notifies
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: release
    uses: banua-coder/banua-coder-workflow/.github/workflows/publish-php.yml@v1
    with:
      php-version: '8.2'
