# Example workflow for web applications (Laravel, Next.js, etc.)
# Copy this file to your project's .github/workflows/release.yml

name: Release

on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    uses: banua-coder/banua-coder-workflow/.github/workflows/release.yml@v1
    with:
      project-type: web-app
      main-branch: main
      develop-branch: develop
      changelog-format: keepachangelog
      auto-merge-backport: false
      node-version: '20'
      php-version: '8.2'
    secrets: inherit

  # Deploy when tag is pushed
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: release
    uses: banua-coder/banua-coder-workflow/.github/workflows/deploy-on-tag.yml@v1
    with:
      environment: production
      deploy-provider: ssh
      deploy-path: /var/www/your-app
    secrets: inherit
